aws:
  region: eu-north-1
  sqs:
    queue-url: https://sqs.eu-north-1.amazonaws.com/192905952216/blood-broker-inbound
    poll-delay-ms: 5000
  sns:
    topic-arn: arn:aws:sns:eu-north-1:192905952216:blood-broker-emergency-alerts
